/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LpButton {
        "callback"?: Function;
    }
    interface LpDropdown {
    }
    interface LpDropdownMenu {
        "options": object[];
    }
}
declare global {
    interface HTMLLpButtonElement extends Components.LpButton, HTMLStencilElement {
    }
    var HTMLLpButtonElement: {
        prototype: HTMLLpButtonElement;
        new (): HTMLLpButtonElement;
    };
    interface HTMLLpDropdownElement extends Components.LpDropdown, HTMLStencilElement {
    }
    var HTMLLpDropdownElement: {
        prototype: HTMLLpDropdownElement;
        new (): HTMLLpDropdownElement;
    };
    interface HTMLLpDropdownMenuElement extends Components.LpDropdownMenu, HTMLStencilElement {
    }
    var HTMLLpDropdownMenuElement: {
        prototype: HTMLLpDropdownMenuElement;
        new (): HTMLLpDropdownMenuElement;
    };
    interface HTMLElementTagNameMap {
        "lp-button": HTMLLpButtonElement;
        "lp-dropdown": HTMLLpDropdownElement;
        "lp-dropdown-menu": HTMLLpDropdownMenuElement;
    }
}
declare namespace LocalJSX {
    interface LpButton {
        "callback"?: Function;
    }
    interface LpDropdown {
    }
    interface LpDropdownMenu {
        "options"?: object[];
    }
    interface IntrinsicElements {
        "lp-button": LpButton;
        "lp-dropdown": LpDropdown;
        "lp-dropdown-menu": LpDropdownMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lp-button": LocalJSX.LpButton & JSXBase.HTMLAttributes<HTMLLpButtonElement>;
            "lp-dropdown": LocalJSX.LpDropdown & JSXBase.HTMLAttributes<HTMLLpDropdownElement>;
            "lp-dropdown-menu": LocalJSX.LpDropdownMenu & JSXBase.HTMLAttributes<HTMLLpDropdownMenuElement>;
        }
    }
}
