/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Options } from "./components/lp-select/lp-select";
export { Options } from "./components/lp-select/lp-select";
export namespace Components {
    interface LpButton {
        "disabled": boolean;
    }
    interface LpSelect {
        "options": Options;
    }
}
declare global {
    interface HTMLLpButtonElement extends Components.LpButton, HTMLStencilElement {
    }
    var HTMLLpButtonElement: {
        prototype: HTMLLpButtonElement;
        new (): HTMLLpButtonElement;
    };
    interface HTMLLpSelectElement extends Components.LpSelect, HTMLStencilElement {
    }
    var HTMLLpSelectElement: {
        prototype: HTMLLpSelectElement;
        new (): HTMLLpSelectElement;
    };
    interface HTMLElementTagNameMap {
        "lp-button": HTMLLpButtonElement;
        "lp-select": HTMLLpSelectElement;
    }
}
declare namespace LocalJSX {
    interface LpButton {
        "disabled"?: boolean;
    }
    interface LpSelect {
        "options"?: Options;
    }
    interface IntrinsicElements {
        "lp-button": LpButton;
        "lp-select": LpSelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lp-button": LocalJSX.LpButton & JSXBase.HTMLAttributes<HTMLLpButtonElement>;
            "lp-select": LocalJSX.LpSelect & JSXBase.HTMLAttributes<HTMLLpSelectElement>;
        }
    }
}
